---
version: '3'
services:

  jupyter:
    build:
      context: ../../
      dockerfile: ./example/docker/jupyter/Dockerfile
      args:
      - FLINK_VERSION=1.15.1
      - ELASTIC_VERSION=8.3.3
    ports:
      - 8888:8888

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    environment:
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
      - "ingest.geoip.downloader.enabled=false"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/"]
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10


  elastic-data:
    build:
      context: ./elastic-data/
    depends_on:
      elasticsearch:
        condition: service_healthy

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 9000:9000
      - 9001:9001
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 user password;
      /usr/bin/mc mb myminio/test-bucket;
      /usr/bin/mc policy set public myminio/test-bucket;
      /usr/bin/mc admin user add myminio flink-sql-runner secretkey;
      /usr/bin/mc admin policy set myminio readwrite user=flink-sql-runner;
      exit 0;
      "

  flink-sql-runner-node:
    build:
      context: ../../
      dockerfile: ./example/docker/flink/Dockerfile
      args:
      - FLINK_VERSION=1.15.1
      - ELASTIC_VERSION=8.3.3
    command: sleep infinity
    environment:
      - AWS_ACCESS_KEY_ID=flink-sql-runner
      - AWS_SECRET_ACCESS_KEY=secretkey
      - AWS_S3_ENDPOINT=http://minio:9000

  jobmanager:
    build:
      context: ../../
      dockerfile: ./example/docker/flink/Dockerfile
      args:
      - FLINK_VERSION=1.15.1
      - ELASTIC_VERSION=8.3.3
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - AWS_ACCESS_KEY_ID=flink-sql-runner
      - AWS_SECRET_ACCESS_KEY=secretkey
      - AWS_S3_ENDPOINT=http://minio:9000
      - ENABLE_BUILT_IN_PLUGINS=flink-s3-fs-hadoop-1.15.1.jar
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - |
        FLINK_PROPERTIES=
        s3.endpoint: http://minio:9000
        s3.path-style-access: true
        s3.access-key: flink-sql-runner
        s3.secret-key: secretkey

  taskmanager:
    build:
      context: ../../
      dockerfile: ./example/docker/flink/Dockerfile
      args:
      - FLINK_VERSION=1.15.1
      - ELASTIC_VERSION=8.3.3
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - AWS_ACCESS_KEY_ID=flink-sql-runner
      - AWS_SECRET_ACCESS_KEY=secretkey
      - AWS_S3_ENDPOINT=http://minio:9000
      - ENABLE_BUILT_IN_PLUGINS=flink-s3-fs-hadoop-1.15.1.jar
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 3
        s3.endpoint: http://minio:9000
        s3.path-style-access: true
        s3.access-key: flink-sql-runner
        s3.secret-key: secretkey
